### ISSUE TITLE
wind shader not working using unity 2019.3.1f1 hdrp 7.20

### ISSUE THREAD

**Issue by GWStudiosDev** [Unity-Technologies/FontainebleauDemo#12]
Hi everyone ....
i downloaded the last version of the FontainebleauDemo everything works fine but the wind in grass and branches and trunk not working ... what can i do to fix it using unity 2019.3.1f1 hdrp 7.20
i got theses errors in Grass_Wind Shader :
'cross': implicit truncation of vector type
Compiling Vertex program with UNITY_PASS_SHADOWCASTER
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

**Comment by Dhrog** [comment]
Those compile warnings can be ignored. 
The actual cause lies in the BasicWindData class:
BasicWind windSettings = VolumeManager.instance.stack.GetComponent<BasicWind>();

I added a BasicWind component to the global Volume stack with the highest prio, but received a null ref as texture. After hard wiring a VolumeProfile as public and fetching the shader values from it, the vegetation started moving.

**Comment by laurenth-personal** [comment]
same here, I couldn't get the VolumeManager to return the correct values.
cc @Chman

**Comment by Chman** [comment]
Fixed on master. The way volumes are updated in HDRP has changed, each camera holds a stack now and the default "main" stack isn't updated by HDRP. So either the user can call update on it or we can just reuse the stack from the current camera which is automatically updated (cheaper).
